const wordList =
[{word:"que",
translations: ["that"]},
{word: "de",
translations: ["of", "from"]},
{word: "no",
translations: ["no"]},
{word: "a",
translations: ["to"]},
{word: "la",
translations: ["the"]},
{word: "el",
translations: ["the"]},
{word: "es",
translations: ["is", "he is", "she is", "it is"]},
{word: "y",
translations: ["and"]},
{word: "en",
translations: ["in", "on", "at"]},
{word: "lo",
translations: ["it", "him"]},
{word: "un",
translations: ["a", "an"]},
{word: "por",
translations: ["for", "by", "through"]},
{word: "qué",
translations: ["what", "how"]},
{word: "me",
translations: ["me", "myself"]},
{word: "una",
translations: ["a", "an"]},
{word: "te",
translations: ["you"]},
{word: "los",
translations: ["the", "them"]},
{word: "se",
translations: ["himself", "herself", "itself"]},
{word: "con",
translations: ["with"]},
{word: "para",
translations: ["for", "to", "in order to"]},
{word:"mi",
translations:["my"]},
{word:"está",
translations:["he is", "she is", "it is"]},
{word:"si",
translations:["if"]},
{word:"bien",
translations:["well", "good"]},
{word:"pero",
translations:["but"]},
{word:"yo",
translations:["i"]},
{word:"eso",
translations:["that", "that one"]},
{word:"las",
translations:["the", "them"]},
{word:"sí",
translations:["yes"]},
{word:"su",
translations:["his", "her", "its"]},
{word:"tu",
translations:["your"]},
{word:"aquí",
translations:["here"]},
{word:"del",
translations:["of the", "from the", "in the"]},
{word:"al",
translations:["to the"]},
{word:"como",
translations:["how", "as", "like"]},
{word:"le",
translations:["him", "her", "you"]},
{word:"más",
translations:["more"]},
{word:"esto",
translations:["this", "this one"]},
{word:"ya",
translations:["already", "anymore", "now"]},
{word:"todo",
translations:["all", "everything"]},
{word:"esta",
translations:["this", "this one"]},
{word:"vamos",
translations:["lets go", "come on"]},
{word:"muy",
translations:["very"]},
{word:"hay",
translations:["there is", "there are"]},
{word:"ahora",
translations:["now"]},
{word:"algo",
translations:["something"]},
{word:"estoy",
translations:["i am"]},
{word:"tengo",
translations:["i have"]},
{word:"nos",
translations:["us"]},
{word:"tú",
translations:["you"]},
{word:"nada",
translations:["nothing"]},
{word:"cuando",
translations:["when"]},
{word:"ha",
translations:["he has", "she has", "it has"]},
{word:"este",
translations:["this", "this one"]},
{word:"sé",
translations:["i know"]},
{word:"estás",
translations:["you are", "youre"]},
{word:"así",
translations:["like this", "like that"]},
{word:"puedo",
translations:["i can"]},
{word:"cómo",
translations:["how"]},
{word:"quiero",
translations:["i want"]},
{word:"sólo",
translations:["only", "just"]},
{word:"soy",
translations:["i am"]},
{word:"tiene",
translations:["he has", "she has", "it has"]},
{word:"gracias",
translations:["thank you", "thanks"]},
{word:"o",
translations:["or"]},
{word:"él",
translations:["he"]},
{word:"bueno",
translations:["good"]},
{word:"fue",
translations:["he was", "she was", "it was"]},
{word:"ser",
translations:["to be"]},
{word:"hacer",
translations:["to do", "to make"]},
{word:"son",
translations:["they are", "you are"]},
{word:"todos",
translations:["all", "all of us", "all of them", "all of you"]},
{word:"era",
translations:["he was", "she was", "it was"]},
{word:"eres",
translations:["you are", "youre"]},
{word:"vez",
translations:["time"]},
{word:"tienes",
translations:["you have"]},
{word:"creo",
translations:["i believe"]},
{word:"ella",
translations:["she"]},
{word:"he",
translations:["i have"]},
{word:"ese",
translations:["that", "that one"]},
{word:"voy",
translations:["i go", "im going"]},
{word:"puede",
translations:["he can", "she can", "it can"]},
{word:"sabes",
translations:["you know"]},
{word:"hola",
translations:["hello", "hi"]},
{word:"sus",
translations:["his", "her", "their"]},
{word:"porque",
translations:["because"]},
{word:"dios",
translations:["god"]},
{word:"quién",
translations:["who"]},
{word:"nunca",
translations:["never"]},
{word:"dónde",
translations:["where"]},
{word:"quieres",
translations:["you want"]},
{word:"casa",
translations:["house"]},
{word:"favor",
translations:["favor"]},
{word:"esa",
translations:["that", "that one"]},
{word:"dos",
translations:["two"]},
{word:"tan",
translations:["so"]},
{word:"señor",
translations:["mister", "sir"]},
{word:"tiempo",
translations:["time", "weather"]},
{word:"verdad",
translations:["truth"]},
{word:"estaba",
translations:["i was", "he was", "she was", "it was"]}
]

export default wordList;
